app = "pixel-positions"
console_command = "php /var/www/html/artisan tinker"
primary_region = "arn"

[build.args]
NODE_VERSION = "18"
PHP_VERSION = "8.2"

[env]
APP_ENV = "production"
APP_URL = "https://pixel-positions.fly.dev/"
DB_CONNECTION = "pgsql"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "info"
LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
SESSION_DRIVER = "cookie"
SESSION_SECURE_COOKIE = "true"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_080
min_machines_running = 0
processes = [ "app" ]

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"


[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
